/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppAnalyzeRouteImport } from './routes/_app.analyze'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppInterviewRouteImport } from './routes/_app.interview'
import { Route as AppJobDescriptionsRouteImport } from './routes/_app.job-descriptions'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppResumesRouteImport } from './routes/_app.resumes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyzeRoute = AppAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewRoute = AppInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AppRoute,
} as any)
const AppJobDescriptionsRoute = AppJobDescriptionsRouteImport.update({
  id: '/job-descriptions',
  path: '/job-descriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesRoute = AppResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analyze': typeof AppAnalyzeRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/interview': typeof AppInterviewRoute
  '/job-descriptions': typeof AppJobDescriptionsRoute
  '/profile': typeof AppProfileRoute
  '/resumes': typeof AppResumesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analyze': typeof AppAnalyzeRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/interview': typeof AppInterviewRoute
  '/job-descriptions': typeof AppJobDescriptionsRoute
  '/profile': typeof AppProfileRoute
  '/resumes': typeof AppResumesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/analyze': typeof AppAnalyzeRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/interview': typeof AppInterviewRoute
  '/_app/job-descriptions': typeof AppJobDescriptionsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/resumes': typeof AppResumesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analyze'
    | '/dashboard'
    | '/history'
    | '/interview'
    | '/job-descriptions'
    | '/profile'
    | '/resumes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analyze'
    | '/dashboard'
    | '/history'
    | '/interview'
    | '/job-descriptions'
    | '/profile'
    | '/resumes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/analyze'
    | '/_app/dashboard'
    | '/_app/history'
    | '/_app/interview'
    | '/_app/job-descriptions'
    | '/_app/profile'
    | '/_app/resumes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/analyze': {
      id: '/_app/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AppAnalyzeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview': {
      id: '/_app/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AppInterviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/job-descriptions': {
      id: '/_app/job-descriptions'
      path: '/job-descriptions'
      fullPath: '/job-descriptions'
      preLoaderRoute: typeof AppJobDescriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumes': {
      id: '/_app/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof AppResumesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyzeRoute: typeof AppAnalyzeRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppInterviewRoute: typeof AppInterviewRoute
  AppJobDescriptionsRoute: typeof AppJobDescriptionsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResumesRoute: typeof AppResumesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyzeRoute: AppAnalyzeRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppInterviewRoute: AppInterviewRoute,
  AppJobDescriptionsRoute: AppJobDescriptionsRoute,
  AppProfileRoute: AppProfileRoute,
  AppResumesRoute: AppResumesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
